discussions/urls.py
# Copyright 2021 Alexandru Cojocaru AGPLv3 or later - no warranty!
import debug_toolbar
from django.contrib import admin
from django.contrib.sitemaps.views import index as sitemap_index, sitemap
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.views.generic.base import TemplateView

from web import api_v0, sitemaps

from . import settings

sitemaps_dict = {
    "static": sitemaps.StaticViewSitemap,
    "weekly": sitemaps.WeeklySitemap,
}

urlpatterns = [
    path("", include("web.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path("api/v0/", api_v0.api.urls),
    path(
        "sitemap.xml",
        cache_page(60 * 60 * 24 * 7, key_prefix="sitemap:")(sitemap_index),
        {"sitemaps": sitemaps_dict, "sitemap_url_name": "sitemaps"},
    ),
    path(
        "sitemap-<str:section>.xml",
        cache_page(60 * 60 * 24 * 7, key_prefix="sitemap:")(sitemap),
        {"sitemaps": sitemaps_dict},
        name="sitemaps",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="robots.txt",
            content_type="text/plain",
            extra_context={
                "sitemap_url": "https://"
                + settings.APP_DOMAIN
                + "/sitemap.xml",
            },
        ),
    ),
    path(
        "2e5ddde867414c0fb0973d5d52044653.txt",
        TemplateView.as_view(
            template_name="2e5ddde867414c0fb0973d5d52044653.txt",
            content_type="text/plain",
        ),
    ),
    path("account/", include("allauth.urls")),
]

web/urls.py
# Copyright 2021 Alexandru Cojocaru AGPLv3 or later - no warranty!
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from . import feed, views

app_name = "web"


urlpatterns = [
    path("", views.index, name="index"),
    path("q/<path:path_q>", views.index, name="index"),
    path("s/<str:platform_id>", views.short_url, name="short_url"),
    path("u/<str:platform_id>", views.story_short_url, name="story_short_url"),
    path("c", views.click, name="click"),
    path(
        "c/<str:type>/<int:subscriber>/<int:year>/<int:week>/<int:discussion>/",
        views.click_subscriber,
        name="click_subscriber",
    ),
    path("weekly/", views.weekly_index, name="weekly_index"),
    path(
        "weekly/confirm_email/",
        views.weekly_confirm_email,
        name="weekly_confirm_email",
    ),
    path(
        "weekly/confirm_unsubscription/",
        views.weekly_confirm_unsubscription,
        name="weekly_confirm_unsubscription",
    ),
    path("weekly/<slug:topic>/", views.weekly_topic, name="weekly_topic"),
    path(
        "weekly/<slug:topic>/<int:year>/<int:week>/",
        views.weekly_topic_week,
        name="weekly_topic_week",
    ),
    path("social/", views.social, name="social"),
    path("twitter/", RedirectView.as_view(url="/social/")),
    path("statistics/", views.statistics, name="statistics"),
    path(
        "extension/",
        TemplateView.as_view(template_name="web/extension.html"),
        name="extension",
    ),
    path(
        "website/",
        TemplateView.as_view(template_name="web/website.html"),
        name="website",
    ),
    path(
        "bookmarklet/",
        TemplateView.as_view(template_name="web/bookmarklet.html"),
        name="bookmarklet",
    ),
    path(
        "search/",
        TemplateView.as_view(template_name="web/search.html"),
        name="search",
    ),
    path(
        "pricing/",
        TemplateView.as_view(template_name="web/pricing.html"),
        name="pricing",
    ),
    path("premium/", RedirectView.as_view(url="/pricing/")),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="web/privacy-policy.html"),
        name="privacy_policy",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="web/terms.html"),
        name="terms",
    ),
    path(
        "support/",
        TemplateView.as_view(template_name="web/support.html"),
        name="support",
    ),
    path(
        "opensearch.xml",
        TemplateView.as_view(
            template_name="web/opensearch.xml",
            content_type="application/opensearchdescription+xml",
        ),
    ),
    path("dashboard/", views.dashboard, name="dashboard"),
    path(
        "dashboard/mentions/",
        views.dashboard_mentions,
        name="dashboard_mentions",
    ),
    path(
        "dashboard/mentions/edit/<int:pk>",
        views.dashboard_mentions_edit,
        name="dashboard_mentions_edit",
    ),
    path(
        "mention_live_preview",
        views.mention_live_preview,
        name="mention_live_preview",
    ),
    path(
        "stripe/checkout/",
        views.stripe_checkout,
        name="stripe_checkout",
    ),
    path(
        "stripe/create-customer-portal-session/",
        views.stripe_create_customer_portal_session,
        name="stripe_create_customer_portal_session",
    ),
    path(
        "stripe/subscribe/success/",
        views.stripe_subscribe_success,
        name="stripe_subscribe_success",
    ),
    path(
        "stripe/subscribe/cancel/",
        views.stripe_subscribe_cancel,
        name="stripe_subscribe_cancel",
    ),
    path("stripe/webhook/", views.stripe_webhook, name="stripe_webhook"),
    path(
        "rss/weekly/<slug:topic>/<slug:rss_id>",
        feed.WeeklyFeed(),
        name="weekly_rss_feed",
    ),
    path(
        "atom/weekly/<slug:topic>/<slug:rs_id>",
        feed.AtomWeeklyFeed(),
        name="weekly_atom_feed",
    ),
    path(
        "rss_single/<slug:topic>/<slug:rss_id>",
        feed.WeeklyFeedSingle(),
        name="weekly_single_rss_feed",
    ),
    path(
        "atom_single/<slug:topic>/<slug:rs_id>",
        feed.AtomWeeklyFeedSingle(),
        name="weekly_single_atom_feed",
    ),
    path("advertise/", views.new_ad, name="new_ad"),
    path(
        "reading/<slug:topic>/",
        views.reading_list_topic,
        name="reading_list_topic",
    ),
    path("api/", views.api_view, name="api"),
    path("mentions/", views.mentions, name="mentions"),
    path(
        "aws_bounce_handler/",
        views.aws_bounce_handler,
        name="aws_bounce_handler",
    ),
]

web/templates/web/admin_statistics.html
{% extends "admin/base_site.html" %}
{% block content %}
{% context.test %}
{% endblock %}

web/templates/web/dashboard.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}
{% load util %}
{% block title %}Dashboard - discu.eu{% endblock %}
{% block main %}
<form method="POST">
    {% csrf_token %}
    {{ ctx.profile_form | crispy }}
    <button type="submit" class="btn btn-secondary" name="submit-update-user-profile">Update profile</button>
</form>
<div class="my-5"></div>
{% if user.is_premium %}
<div class="card">
    <h5 class="card-header">Premium plan</h5>
    <div class="card-body">
        <p class="card-text">
            Renew or cancel your premium plan. Update payment methods, billing information or
            see
            invoices.
        </p>
        <form method="POST" action="{% url 'web:stripe_create_customer_portal_session' %}">
            {% csrf_token %}
            <input type="hidden" name="return_to_path" value="{{ request.get_full_path }}">
            <button type="submit" class="btn btn-secondary">Manage premium plan</button>
        </form>
    </div>
</div>
{% else %}
{% if ctx.user_verified_email %}
<div class="card" id="dashboard-get-premium">
    <h5 class="card-header">Premium plan</h5>
    <div class="card-body">
        <p class="card-text">
            Get RSS feeds, an ad-free experience and <a href="{% url 'web:pricing' %}"
                title="Pricing and features">more!</a>
        </p>
        <form method="POST" action="{% url 'web:stripe_checkout' %}">
            {% csrf_token %}
            <input type="hidden" name="return_to_path" value="{{ request.get_full_path }}">
            <button type="submit" class="btn btn-primary">Go premium!</button>
        </form>
    </div>
</div>
{% endif %}
{% endif %}
<div class="my-5"></div>
<h4>Newsletter subscriptions</h4>
{% if ctx.subscriptions %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="table-info">
            <tr>
                <th scope="col">Topic</th>
                <th scope="col">Email</th>
                <th scope="col">Email confirmed?</th>
                <th scope="col">Still subscribed?</th>
            </tr>
        </thead>
        <tbody>
            {% for sub in ctx.subscriptions %}
            <tr>
                <td>{{ ctx.topics|get_item:sub.topic|get_item:'name' }}</td>
                <td>{{ sub.email }}</td>
                <td>
                    {% if sub.confirmed %}
                    <span class="text-success">Yes</span>
                    {% else %}
                    <span class="text-danger">No</span>
                    {% endif %}
                </td>
                <td>
                    {% if sub.unsubscribed %}
                    <span class="text-danger">No</span>
                    {% else %}
                    <span class="text-success">Yes</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<p>
    Check out all <a href="/weekly/">the newsletters</a>.
</p>
{% else %}
<p>
    You have no subscriptions yet. Make sure you have verified <a href="{% url 'account_email' %}"
        title="Manage your emails">all your emails</a> or subscribe <a href="/weekly/">to a newsletter</a>.
</p>
{% endif %}
{% if user.rss_id %}
<h4 class="mt-5">RSS feeds</h4>
{% if not user.is_premium %}
<p class="alert alert-warning py-3">
    The following RSS feeds contain old sample issues.
    Get the <a href="#dashboard-get-premium">premium plan</a> to access complete feeds.
</p>
{% endif %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="table-info">
            <tr>
                <th scope="col">Topic</th>
                <th scope="col">RSS feed</th>
            </tr>
        </thead>
        <tbody>
            {% for topic_key, topic in ctx.topics.items %}
            <tr>
                <td>
                    <a href="{% url 'web:weekly_topic' topic_key %}" class="text-body">{{ topic.name }}</a>
                </td>
                <td>
                    <a href="{% url 'web:weekly_rss_feed' topic_key user.rss_id %}"><span class="bi bi-rss"></span></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<p class="smaller-font-4 alert alert-info">These feeds are personal, please don't share them with anyone.</p>
{% endif %}
<div class="card mt-5">
    <h5 class="card-header">Manage mention rules</h5>
    <div class="card-body">
        <p class="card-text">Update, add and delete mention rules.</p>
        {% if ctx.user_verified_email %}
        <a href="{% url 'web:dashboard_mentions' %}" class="btn btn-secondary">Mentions</a>
        {% else %}
        <p class="card-text alert alert-warning">
            Verify your <a href="{% url 'account_email' %}" title="Manage your emails">email</a> to create a new mention
            rule
        </p>
        {% endif %}
    </div>
</div>
<div class="my-5"></div>
<div class="card">
    <h5 class="card-header">Manage emails</h5>
    <div class="card-body">
        <p class="card-text">Update, add, delete and verify your emails.</p>
        <a href="{% url 'account_email' %}" class="btn btn-secondary">My emails</a>
    </div>
</div>
<div class="my-5"></div>
{% if user.api %}
<div class="card">
    <h5 class="card-header">Discussions API</h5>
    <div class="card-body">
        {% if ctx.user_verified_email %}
        <p class="card-text">API token: {{ user.api.token }}</p>
        {% else %}
        <p class="card-text">
            API token: <span class="alert alert-warning">verify your email to get an API
                token</span>
        </p>
        {% endif %}
        <p>
            <a href="{% url 'api-v0:openapi-view' %}" class="btn btn-info">API documentation</a>
        </p>
    </div>
</div>
{% endif %}
<div class="my-5"></div>
<div class="card">
    <h5 class="card-header">Contacts</h5>
    <div class="card-body">
        <div class="card-text">
            Check out our <a href="https://www.reddit.com/r/discueu/" title="Discu.eu's subreddit">subreddit</a> for
            questions,
            feedback or support.
        </div>
        {% if user.is_premium %}
        <div class="card-text mt-1">
            To contact us by email write to <a href="mailto:support@discu.eu">support@discu.eu</a>.
        </div>
        {% else %}
        <div class="card-text mt-1">
            Get the <a href="#dashboard-get-premium" title="Premium plan">premium plan</a> for
            email
            support.
        </div>
        {% endif %}
    </div>
</div>
<div class="mb-5"></div>
{% endblock main %}

web/templates/web/discussions.html
{% extends "web/base.html" %}
{% load humanize %}
{% load util %}
{% load static %}
{% block title %}
    {% if ctx.title or ctx.original_query %}
        {% firstof ctx.title ctx.original_query %} - discu.eu
    {% else %}
        Discussions around the Web - discu.eu
    {% endif %}
{% endblock title %}
{% block meta_description %}
    {% if ctx.title or ctx.original_query %}
        Discussions and related articles for «{% firstof ctx.title ctx.original_query %}»
    {% else %}
        Find interesting discussions on Hacker News, Reddit and Lobsters for a given URL, title or keyword.
    {% endif %}
{% endblock meta_description %}
{% block extra_head %}
    {% if ctx.link_canonical_url %}<link rel="canonical" href="{{ ctx.link_canonical_url }}" />{% endif %}
{% endblock extra_head %}
{% block main %}
    <div id="discussions">
        <form method="get" action="/">
            <div class="d-flex flex-row gap-1">
                <input class="flex-fill"
                       id="q"
                       name="q"
                       type="text"
                       autofocus
                       onfocus="this.selectionStart = this.selectionEnd = this.value.length;"
                       value="{{ ctx.original_query }}"
                       placeholder="URL or title" />
                <button type="submit" value="" class="btn btn-primary">
                    <span class="bi bi-search fw-bold"></span>
                </button>
            </div>
        </form>
        <!-- {% if not ctx.nothing_found and not ctx.display_discussions %}
	<p class="smaller-font-3">See some <a href="{% url 'web:search' %}" title="How to search">search
			examples</a>.</p>
{% endif %} -->
        <div class="my-4"></div>
        <!--
	 SQL query:

	 {{ctx.sql_query}}
-->
        {% if ctx.nothing_found %}
            <h4>Discussions not found</h4>
            <p>
                Sorry, we couldn't find anything for <strong>{{ ctx.url }}</strong>.
            </p>
            <p class="smaller-font-1">
                See some <a href="{% url 'web:search' %}" title="How to search">search examples</a>.
            </p>
        {% else %}
            {% if ctx.display_discussions %}
                {% for platform, platform_name, platform_url, platform_tag_url, discussions in ctx.grouped_discussions %}
                    <div id="platform_{{ platform }}" class="platform_discussions">
                        <h6>{{ platform_name }}</h6>
                    </div>
                    <ul class="list-unstyled">
                        {% for d in discussions %}
                            <li class="mb-2">
                                <a href="{{ d.story_url }}"
                                   title="{{ d.title }}"
                                   class="d-flex flex-column text-body"
                                   rel="nofollow">
                                    {{ d.title }}
                                    <span class="d-inline-block smaller-font url-max-width text-truncate">{{ d.story_url }}</span></a>
                                <a href="{{ d.discussion_url }}"
                                   title="View discussion with {{ d.score }} {{ d.platform.score_label }} on {{ platform_name }}"
                                   rel="nofollow"><strong>{{ d.comment_count }}
                                comment{{ d.comment_count|pluralize:",s" }}</strong></a>
                                <span class="smaller-font"><time datetime="{{ d.created_at | date:'c' }}">{{ d.created_at | date }}</time></span>
                                <span class="smaller-font">
                                    {% if d.tags %}
                                        {% if platform != 'r' %}{% endif %}
                                        {% for tag in d.tags %}
                                            {{ tag }}
                                            {% if not forloop.last %},{% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </span>
                                <!--Id: {{d.platform_id}}
		 Normalized tags: {{d.normalized_tags}}
		 Normalized title: {{d.normalized_title}}
		 Canonical url: {{d.canonical_story_url}}
-->
                            </li>
                            {% if forloop.parentloop.counter == 1 and forloop.counter == 1 %}
                                <script async
                                        type="text/javascript"
                                        src="//cdn.carbonads.com/carbon.js?serve=CWYI62QL&placement=discueu"
                                        id="_carbonads_js"></script>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endfor %}
            {% else %}
                <h1 class="mt-5 text-center">
                    Keep up with the topics <span class="highlight">you</span> care about
                </h1>
                <div class="d-flex flex-row flex-wrap gap-5 text-center justify-content-center mb-5">
                    <div class="w-min-content w-min-16ch">
                    <a href="{% url 'web:weekly_index' %}"
                       title="Weekly newsletters"
                       class="text-underline-hover text-body"><i class="bi bi-newspaper m-auto text-primary fs-5em"></i>
                    <h3>Weekly newsletters</h3>
                    <span class="lead mb-0">Each week on topic recaps with articles, projects and
                    tutorials.</span>
                </a>
            </div>
            <div class="w-min-content w-min-16ch">
            <a href="{% url 'web:extension' %}"
               class="text-underline-hover text-body"
               title="Discussions browser extension"><i class="bi bi-browser-firefox m-auto text-primary fs-5em"></i>
            <h3>Browser extension</h3>
            <span class="lead mb-0">See if the page you are on has been discussed before.</span>
        </a>
    </div>
    <div class="w-min-content w-min-16ch">
    <a href="{% url 'web:social' %}"
       class="text-underline-hover text-body"
       title="Social accounts and bots"><i class="bi bi-twitter m-auto text-primary fs-5em"></i>
    <h3>Twitter & Mastodon</h3>
    <span class="lead mb-0">On topic bots posting articles, projects and tutorials.</span>
</a>
</div>
</div>
<h2 class="fs-3 mt-4em text-center mb-4">Are you a developer?</h2>
<div class="d-flex flex-row flex-wrap gap-5 text-center justify-content-center mb-5">
    <div class="w-min-content w-min-16ch">
    <a href="{% url 'web:mentions' %}"
       class="text-underline-hover text-body"
       title="Mentions"><i class="bi bi-activity m-auto text-dark fs-2em"></i>
    <h3 class="fs-4">Mentions</h3>
    <span class="mb-0">Get notified when you're mentioned and jump into the
    conversation.</span>
</a>
</div>
<div class="w-min-content w-min-16ch">
<a href="{% url 'web:api' %}"
   title="Discussions and comments API"
   class="text-underline-hover text-body"><i class="bi bi-plug m-auto text-dark fs-2em"></i>
<h3 class="fs-4">API</h3>
<span class="mb-0">Lookup millions of discussions across different platforms.</span>
</a>
</div>
<div class="w-min-content w-min-16ch">
<a href="{% url 'web:website' %}"
   class="text-underline-hover text-body"
   title="Discussions for your website"><i class="bi bi-link-45deg m-auto text-dark fs-2em"></i>
<h3 class="fs-4">Website</h3>
<span class="mb-0">Discussions from the web directly on your website.</span>
</a>
</div>
</div>
{% endif %}
{% endif %}
<!-- Resource id: {{ctx.resource.id}} -->
{% if ctx.inbound_resources %}
    <div class="my-5"></div>
    <h6>Linking pages</h6>
    <div class="inbound_links">
        <ul class="list-unstyled">
            {% for inbound_resource in ctx.inbound_resources %}
                <!-- Inbound resource id: {{inbound_resource.id}} -->
                <li class="mb-2">
                    <a href="{{ inbound_resource.complete_url }}"
                       title="{% firstof inbound_resource.title inbound_resource.complete_url %}"
                       rel="nofollow"
                       class="d-flex flex-column text-body">
                        {{ inbound_resource.title }}
                        <span class="d-inline-block smaller-font url-max-width text-truncate">{{ inbound_resource.complete_url }}</span>
                    </a>
                    <a href="{{ inbound_resource.complete_url | discussions_url }}"
                       title="Discussions for «{% firstof inbound_resource.title inbound_resource.complete_url %}»">
                        <strong>{{ inbound_resource.discussions_comment_count }}
                        comment{{ inbound_resource.discussions_comment_count|pluralize:",s" }}</strong>
                    </a>
                    <!-- Pagerank: {{inbound_resource.pagerank}} -->
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
{% if ctx.outbound_resources %}
    <div class="my-5"></div>
    <h6>Linked pages</h6>
    <div>
        <ul class="list-unstyled">
            {% for outbound_resource in ctx.outbound_resources %}
                <!-- Outbound resource id: {{outbound_resource.id}} -->
                <li class="mb-2">
                    <a href="{{ outbound_resource.complete_url }}"
                       title="{% firstof outbound_resource.title outbound_resource.complete_url %}"
                       rel="nofollow"
                       class="d-flex flex-column text-body">
                        {{ outbound_resource.title }}
                        <span class="d-inline-block smaller-font url-max-width text-truncate">{{ outbound_resource.complete_url }}</span>
                    </a>
                    <a href="{{ outbound_resource.complete_url | discussions_url }}"
                       title="Discussions for «{% firstof outbound_resource.title outbound_resource.complete_url %}»">
                        <strong>{{ outbound_resource.discussions_comment_count }}
                        comment{{ outbound_resource.discussions_comment_count|pluralize:",s" }}</strong>
                    </a>
                    <!-- Pagerank: {{outbound_resource.pagerank}} -->
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<div class="mt-5"></div>
{% if ctx.suggested_topic %}
    <div class="smaller-font-2 mb-3">
        Would you like to stay up to date with {{ ctx.suggested_topic_name }}? Checkout <a href="{% url 'web:weekly_topic' ctx.suggested_topic %}"
    title="{{ ctx.suggested_topic_short_description }} newsletter">{{ ctx.suggested_topic_name }}
        Weekly</a>.
    </div>
{% endif %}
{% if ctx.try_with_site_prefix or ctx.try_with_title %}
    <details {% if ctx.nothing_found %}open{% endif %} class="smaller-font-2">
        <summary>Related searches:</summary>
        {% if ctx.try_with_site_prefix %}
            <p class="mb-1 ms-3">
                Search whole site: <a href="{{ ctx.try_with_site_prefix|discussions_url }}"
    title="Discussions for «{{ ctx.try_with_site_prefix }}»"
    rel="nofollow">{{ ctx.try_with_site_prefix }}</a>
            </p>
        {% endif %}
        {% if ctx.try_with_title %}
            <p class="mb-1 ms-3">
                Search title: <a href="{{ ctx.try_with_title|discussions_url }}"
    title="Discussions for «{{ ctx.try_with_title }}»"
    rel="nofollow">{{ ctx.try_with_title }}</a>
            </p>
        {% endif %}
        {% if ctx.try_with_url %}
            <p class="mb-1 ms-3">
                Lookup url: <a href="{{ ctx.try_with_url|discussions_url }}"
    title="Discussions for «{{ ctx.try_with_url }}»"
    rel="nofollow">{{ ctx.try_with_url }}</a>
            </p>
        {% endif %}
        <p class="mt-1 mb-1 ms-3 smaller-font-1">
            See <a href="{% url 'web:search' %}" title="How to search discussions">how
            to search</a>.
        </p>
    </details>
{% endif %}
{% if ctx.submit_links %}
    <div class="submit_links smaller-font-2 mt-2">
        <details {% if ctx.submit_links_visible %}open{% endif %}>
            <summary>Submit link to:</summary>
            <ul>
                {% for submit_platform, submit_link in ctx.submit_links.items %}
                    <li>
                        <a href="{{ submit_link }}"
                           title="Submit to {{ submit_platform }}"
                           rel="nofollow noreferrer noopener"
                           target="_blank">{{ submit_platform }}</a>
                    </li>
                {% endfor %}
            </ul>
        </details>
    </div>
{% endif %}
</div>
{% endblock main %}

web/templates/web/twitter.html
{% extends "web/base.html" %}


{% block main %}

<h2>Twitter Bots</h2>
<p>
	The following bots tweet regularly the most interesting discussions about some particular topic:
</p>

<ul>
	<li><a href="https://twitter.com/IntPyDiscu" title="Python Twitter bot">@IntPyDiscus</a> - Python discussions</li>
	<li><a href="https://twitter.com/RustDiscussions" title="Rust Twitter bot">@RustDiscussions</a> - Rust discussions</li>
</ul>

<br/>

<p>
	You can find me at <a href="https://twitter.com/XojocXojoc" title="Twitter profile of Alexandru Cojocaru">@XojocXojoc</a>.
</p>


{% endblock main %}

web/templates/web/website.html
{% extends "web/base.html" %}

{% load util %}

{% block title %}
Discussions and comments for your website - discu.eu
{% endblock title %}

{% block meta_description %}
Display discussions and comments across platforms (Hacker News, Reddit, Lobsters, etc.) on your website or blog.
{% endblock %}

{% block main %}

<h2>Display comments on your website</h2>
<p>
    To display discussions for a page on your website or blog, just include a link to discu.eu:

<pre>
    https://discu.eu/?q=<b>URL</b>&submit_title=<b>article title</b></pre>

where <b>URL</b> is the address of your page and <b>submit_title</b> is an optional parameter, which when included is
used to prefill the submission title if the user
decides to submit your story to a platform.
</p>

<p>Discussions are fetched from Hacker News, Reddit, Lobsters and <a href="{% url 'web:statistics' %}#platforms"
        title="Platforms">others</a> and are updated frequently.</p>

<p>
    If you want to include a link only on pages with relevant dicussions then call our <a href="{% url 'web:api' %}"
        title="Discussions API">API</a> first (use the <b>discussions_counts</b> method).
</p>
<p>
    The API returns the comments and discussions count for each platform and subreddit. This way
    you
    can include a link only if you're interested in a specific platform or subreddit.
</p>

<p>
    Check out Bèr's tutorial on how to <a
        href="https://berk.es/2022/10/12/blog-comments-on-a-static-site-via-social-networks/"
        title="Blog comments on a static site via social networks">display discussions on a static website</a>.
</p>

<h3 class="fs-4">Examples</h3>
<ul>
    <li><a href="https://comment.ctrl.blog/discussion/dht-privacy-discovery-hash">How a Hypercore P2P innovation could
            bring more privacy to IPFS</a> on Ctrl.blog which points to <a
            href="https://discu.eu/?q=https%3A%2F%2Fwww.ctrl.blog%2Fentry%2Fdht-privacy-discovery-hash.html&submit_title=How%20a%20Hypercore%20P2P%20innovation%20could%20bring%20more%20privacy%20to%20IPFS">the
            following discussions</a>.
    <li>See section "Comments and Discussions" on <a href="https://berk.es/2022/09/28/value-objects-in-rust/"
            title="Value Objects in Rust">Bèr</a>'s
        blog.</li>
    <li>See the bottom of this <a href="https://xojoc.pw/blog/focus" title="Example article">article</a>
        which includes the following
        <a
            href="https://discu.eu/?q=https://xojoc.pw%2fblog%2ffocus&submit_title=Why%20I%27m%20focusing%20only%20on%20some%20programming%20languages">link</a>.
    </li>
</ul>


<h2 class="fs-4">Widget</h2>
<p>
    Use <a href="https://github.com/berkes/discueu.js" title="discueu.js">berkes/discueu.js</a> as a template to include
    discussions on
    your blog or website.
</p>


<h4 class="fs-5 mt-4">Whole site search</h4>
<p>
    Pro tip: if would like to see all the discussions for your whole site, use the <b>site:</b> prefix when searching.
    Example <a href="{{'site:xojoc.pw'|discussions_url}}" title="Whole site search">site:xojoc.pw</a>.
</p>
{% endblock main %}